In [ ]:
from google.colab import files

uploaded = files.upload()

Saving creditcard.csv to creditcard (1).csv

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models,layers
from sklearn.model_selection import train_test_split
from tensorflow.keras.regularizers import l2

In [ ]:
data=pd.read_csv('creditcard (1).csv')
data

            Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284807 rows x 31 columns]

In [ ]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
data

                Time            V1  ...         Amount          Class
count  284807.000000  2.848070e+05  ...  284807.000000  284807.000000
mean    94813.859575  3.919560e-15  ...      88.349619       0.001727
std     47488.145955  1.958696e+00  ...     250.120109       0.041527
min         0.000000 -5.640751e+01  ...       0.000000       0.000000
25%     54201.500000 -9.203734e-01  ...       5.600000       0.000000
50%     84692.000000  1.810880e-02  ...      22.000000       0.000000
75%    139320.500000  1.315642e+00  ...      77.165000       0.000000
max    172792.000000  2.454930e+00  ...   25691.160000       1.000000

[8 rows x 31 columns]

In [ ]:
time_means=data.Time.mean(axis=0)
time_std=data.Time.std(axis=0)
data.Time-=time_means
data.Time/=time_std

In [ ]:
amount=data.Amount.mean(axis=0)
amount_std=data.Amount.std(axis=0)
data.Amount-=amount
data.Amount/=amount_std
data

            Time         V1         V2  ...       V28    Amount  Class
0      -1.996580  -1.359807  -0.072781  ... -0.021053  0.244964      0
1      -1.996580   1.191857   0.266151  ...  0.014724 -0.342474      0
2      -1.996558  -1.358354  -1.340163  ... -0.059752  1.160684      0
3      -1.996558  -0.966272  -0.185226  ...  0.061458  0.140534      0
4      -1.996537  -1.158233   0.877737  ...  0.215153 -0.073403      0
...          ...        ...        ...  ...       ...       ...    ...
284802  1.641929 -11.881118  10.071785  ...  0.823731 -0.350150      0
284803  1.641950  -0.732789  -0.055080  ... -0.053527 -0.254116      0
284804  1.641971   1.919565  -0.301254  ... -0.026561 -0.081839      0
284805  1.641971  -0.240440   0.530483  ...  0.104533 -0.313248      0
284806  1.642055  -0.533413  -0.189733  ...  0.013649  0.514354      0

[284807 rows x 31 columns]

In [ ]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [ ]:
x_tran,x_test,y_tran,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_tran, x_val, y_tran, y_val = train_test_split(x_tran, y_tran, test_size=0.3, random_state=0)

In [ ]:
model=models.Sequential()
model.add(layers.Dense(6, activation= 'relu',kernel_regularizer=l2(0.01),input_shape=(30,)))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(6, activation= 'relu',kernel_regularizer=l2(0.01)))
model.add(layers.Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy', metrics= ['accuracy'])
model.fit(x_tran, y_tran,epochs=5,validation_data=(x_val, y_val))

Epoch 1/5
4985/4985 [==============================] - 8s 1ms/step - loss: 0.3182 - accuracy: 0.9104 - val_loss: 0.0130 - val_accuracy: 0.9981
Epoch 2/5
4985/4985 [==============================] - 7s 1ms/step - loss: 0.0122 - accuracy: 0.9984 - val_loss: 0.0130 - val_accuracy: 0.9981
Epoch 3/5
4985/4985 [==============================] - 7s 1ms/step - loss: 0.0120 - accuracy: 0.9983 - val_loss: 0.0130 - val_accuracy: 0.9981
Epoch 4/5
4985/4985 [==============================] - 7s 1ms/step - loss: 0.0116 - accuracy: 0.9984 - val_loss: 0.0127 - val_accuracy: 0.9981
Epoch 5/5
4985/4985 [==============================] - 7s 1ms/step - loss: 0.0124 - accuracy: 0.9983 - val_loss: 0.0127 - val_accuracy: 0.9981

In [ ]:
model.evaluate(x_test,y_test)

1781/1781 [==============================] - 2s 868us/step - loss: 0.0121 - accuracy: 0.9982

[0.012127536348998547, 0.9982268810272217]

In [ ]:
model.predict(x_test)

array([[0.00144181],
       [0.00140578],
       [0.00137785],
       ...,
       [0.0013985 ],
       [0.00144371],
       [0.00130957]], dtype=float32)

In [ ]:
y_test[y_test>0]

83053     1
221041    1
6717      1
263080    1
231978    1
         ..
220725    1
52584     1
151807    1
154697    1
248971    1
Name: Class, Length: 101, dtype: int64